### ISSUE TITLE
下载的图片文件又打不开了...

### ISSUE THREAD

**Issue by okhoogh** [kajweb/wqxuetang_downloader#14]
服了和我们对线的老哥了

**Comment by Kuoliang-Chung** [comment]
是的呢。。。
对面是改了什么东西啊

**Comment by okhoogh** [comment]
布吉岛，我就差一点就完事了，，，

**Comment by kajweb** [comment]
又打不开……服了

**Comment by kajweb** [comment]
我去试试

**Comment by okhoogh** [comment]
奥利给老哥ヾ(◍°∇°◍)ﾉﾞ

**Comment by kajweb** [comment]
我这边还有事，空白你就重新运行吧。
确定是最新版本。

**Comment by okhoogh** [comment]
我重新下载zip来运行还是不行...

**Comment by kajweb** [comment]
我也喜提空白图片。这个你删除不能打开的图片、重新启动下载就行了。

**Comment by okhoogh** [comment]
我把整个IMG文件夹删了，然后重新下，然鹅不行qwq

**Comment by kajweb** [comment]
完了，那个老哥生气了直接把IP拉黑了？

你看看[直接阅读](https://lib-nuanxin.wqxuetang.com/read/pdf/191950)能不能加载到

**Comment by okhoogh** [comment]
不能，网页一直转圈圈，该不会只封了我的吧...

**Comment by okhoogh** [comment]
左上角还有个小的图片标识

**Comment by okhoogh** [comment]
好像不是封ip，他们可能把数据库关了吧，我开vpn一样是转圈圈

**Comment by kajweb** [comment]
好像真的被封了IP。重启路由器重新获取IP就可以了。
是不是你访问频率太快了

**Comment by kajweb** [comment]
我重启路由器就好了

**Comment by okhoogh** [comment]
我也好了haha

**Comment by okhoogh** [comment]
他现在好像弄了个自动封ip的玩意了

**Comment by kajweb** [comment]
我觉得是后面有一个人在那边一顿操作。算了，睡觉去了。不行明天上代理了

**Comment by okhoogh** [comment]
嗯，早安

**Comment by Cybersariel** [comment]
现在下载的去全是空白图片
