### ISSUE TITLE
需要同学优化一下PDF

### ISSUE THREAD

**Issue by kajweb** [kajweb/wqxuetang_downloader#15]
- 在wqxtDownloader __init__()增加一个方法将链接转换为bid
- 在wqxtDownloader __init__()增加一个方法检测bid是否正确
- 在wqxtDownloader initread()返回数据接口时，检测是否返回`{"data":[],"errcode":8003,"errmsg":"很抱歉，您访问的图书不存在"} `

**Comment by kajweb** [comment]
现在文件太大了，能否压缩一下jpg，或者调整一下jpg质量。
关键字：tinypng

**Comment by lovejun277** [comment]
还有没有人出来解决难题的啊 清华大学太恶心了




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "kajweb"<notifications@github.com&gt;; 
发送时间: 2020年2月9日(星期天) 晚上10:42
收件人: "kajweb/wqxuetang_downloader"<wqxuetang_downloader@noreply.github.com&gt;; 
抄送: "Subscribed"<subscribed@noreply.github.com&gt;; 
主题: Re: [kajweb/wqxuetang_downloader] 需要同学优化一下PDF (#15)




Closed #15.
