### ISSUE TITLE
提示获取到了失败的图片

### ISSUE THREAD

**Issue by hgjsjby518** [kajweb/wqxuetang_downloader#16]
前面下载了一些图片文件还正常，但后面就无法下载了，先是表现为得到的图片文件大小只有5字节。中断程序运行后删除这些无效图片文件，再重新运行后就提示“获取到了失败的图片”，是否是被封了？该怎么解决？谢谢！

**Comment by hgjsjby518** [comment]
重启路由器好了，看来是被封了

**Comment by kajweb** [comment]
由于网站策略问题，当前IP地址暂时失效
