### ISSUE TITLE
生成pdf代码有一本书遇到问题

### ISSUE THREAD

**Issue by ntuchenxy** [kajweb/wqxuetang_downloader#17]
3207901，291张图，我重复下载了两次，每张图都看过都没有问题，但是转换PDF时报Invalid argument，我不清楚里面哪张图有问题导致的，能否提供些解决或者发现问题的思路？下了十多本书，就这个遇到问题了

**Comment by kajweb** [comment]
这个自行用其他软件合成试试，或者直接使用命令行合成。

https://pypi.org/project/img2pdf/

`$ img2pdf img1.png img2.jpg -o out.pdf`
