### ISSUE TITLE
pymupdf安装失败

### ISSUE THREAD

**Issue by i-CraftY** [kajweb/wqxuetang_downloader#18]
Win7
`Collecting pymupdf
  Using cached PyMuPDF-1.16.10.tar.gz (175 kB)
Installing collected packages: pymupdf
    Running setup.py install for pymupdf ... error
    ERROR: Command errored out with exit status 1:
     command: 'c:\users\administrator\appdata\local\programs\python\python38-32\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Administrator\\AppData\\Local\\Temp\\pip-install-ifcv86oe\\pymupdf\\setup.py'"'"'; __file__='"'"'C:\\Users\\Administrator\\AppData\\Local\\Temp\\pip-install-ifcv86oe\\pymupdf\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\Administrator\AppData\Local\Temp\pip-record-j9ktdftz\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\users\administrator\appdata\local\programs\python\python38-32\Include\pymupdf'
         cwd: C:\Users\Administrator\AppData\Local\Temp\pip-install-ifcv86oe\pymupdf\
    Complete output (13 lines):
    running install
    running build
    running build_py
    creating build
    creating build\lib.win32-3.8
    creating build\lib.win32-3.8\fitz
    copying fitz\__init__.py -> build\lib.win32-3.8\fitz
    copying fitz\fitz.py -> build\lib.win32-3.8\fitz
    copying fitz\utils.py -> build\lib.win32-3.8\fitz
    copying fitz\__main__.py -> build\lib.win32-3.8\fitz
    running build_ext
    building 'fitz._fitz' extension
    error: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": https://visualstudio.microsoft.com/downloads/
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'c:\users\administrator\appdata\local\programs\python\python38-32\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Administrator\\AppData\\Local\\Temp\\pip-install-ifcv86oe\\pymupdf\\setup.py'"'"'; __file__='"'"'C:\\Users\\Administrator\\AppData\\Local\\Temp\\pip-install-ifcv86oe\\pymupdf\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\Administrator\AppData\Local\Temp\pip-record-j9ktdftz\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\users\administrator\appdata\local\programs\python\python38-32\Include\pymupdf' Check the logs for full command output.`

**Comment by kajweb** [comment]
不清楚，要不换源试试。
