### ISSUE TITLE
关于代理，我发现了这个项目，不知有没有用

### ISSUE THREAD

**Issue by litengde** [kajweb/wqxuetang_downloader#19]
https://github.com/jhao104/proxy_pool

**Comment by kajweb** [comment]
很早前看过，还需要自己爬，可能有不稳定因素。所以不采用。

**Comment by litengde** [comment]
> 很早前看过，还需要自己爬，可能有不稳定因素。所以不采用。

不用弄了，慢慢来又不会封IP
