### ISSUE TITLE
说的过了，早上看到这样的事确实有点过激。但是对我而言，我仍然不敢苟同。

### ISSUE THREAD

**Issue by aeof** [kajweb/wqxuetang_downloader#21]
我可能觉得你想秀一秀自己的技术，或者是为了“造福”不想花钱的人。但是你明知这是窃取别人的知识产权，破坏计算机系统，还发布这样的程序，实在是有悖于技术伦理。在疫情下，你这样说是吃人血馒头也不为过；即使不是在疫情下，这也属于无良的技术。没有利益相关，我只是觉得，如果一个技术人没有技术伦理，无异于高知识的犯罪分子，更让人愤恨！

**Comment by TheGayhub** [comment]
你好，我对于这件事情是这么认为的。这已经给我们免费开放了，不需要花钱。我们每个人都可以一张一张的把pdf保存下来，但是那样会浪费我们的时间，这个下载器可以简化我们的时间。

**Comment by aeof** [comment]
但是这并不是永久免费的，即使是永久免费的，现在网站也服务不正常了。我觉得你会自己爬取就算了，但是放在一个公共的地方，很容易被那些怀心思的人制作贩卖，影响网站的收益。有点像你自己公司的产品被窃取了，你自己的程序被人破解了订阅，你怎么想。

**Comment by TheGayhub** [comment]
嗯，网站顶不住了

**Comment by iMicroSoftever** [comment]
看楼上说的，哈哈。
这项目没几个人知道，你怎么找到的?还不是想下载？自己不会用干着急(技术？)就说别人不道德，五十步笑百步。
谁给你承认知识产权这种事的?美国的规则我没义务遵守。靠信息不对称来赚钱(赚，骗也)难道就契合你的价值观？（按你的价值观:只许州官放火，不许百姓点灯)

你可以无益于社会，但不要甘心为小人!

**Comment by aeof** [comment]
第一点，我是在算法群里发现有人分享的；第二点，少数人知道就能盗版？；怎么又来信息不对称了，靠技术爬取pdf贩卖我没说支持；第四点，你可以自己偷偷盗版，但不要宣扬盗版技术。

**Comment by litengde** [comment]
别吵了，哈哈哈
git 上一般都是 研究，应该不会出现所说的贩卖什么的🥴

**Comment by s1eke** [comment]
我觉得吧，如果有爬完的大佬直接分享出来就更好了，减轻服务器的压力（伸手党😂

**Comment by go-bai** [comment]
> 看楼上说的，哈哈。
> 这项目没几个人知道，你怎么找到的?还不是想下载？自己不会用干着急(技术？)就说别人不道德，五十步笑百步。
> 谁给你承认知识产权这种事的?美国制定的规则我没义务遵守。靠信息不对称来赚钱(赚，骗也)难道就契合你的价值观？（按你的价值观:只许州官放火，不许百姓点灯)
> 
> 你可以无益于社会，但不要甘心为小人!

没几个人知道？你不知道互联网传播的速度？

**Comment by okhoogh** [comment]
这是一个方便我们的工具，哪里有盗版的性质？难道说一个人用刀杀了人，还要怪制作刀的人吗？

**Comment by litengde** [comment]
别争了，哇。都是玩代码的，别伤了和气~~~~

**Comment by ImwangXM** [comment]
**少扯，诸君若是腰缠万贯，谁还搁这跟您 哈讲道理**

**Comment by ysbwss** [comment]
你简直就是在偷换概念了兄弟 
  1、首先官网是免费开放的 而且这里是玩代码的地方 并且下载了我们只适用于学术研究 并不存在倒卖行为 就算有倒卖行为 就跟你是卖刀的 有人从你这里买了刀杀了人  警察会抓你还是抓他？况且作者已经声明仅用于学术研究下载后24小时内删除。
2、你所说的知识产权。知识产权他是卖给了出版社   现在出版社限时免费开放，而且我们下载的书只是看并没有对他书中的内容进行修改或者是抨击  所以本身并没有构成侵权
3、你所说的盗版的问题   你记得新闻怎么说的吗？所有正版图书免费限时开放  我就不知道你怎么能下的是盗版？
4、纯个人立场：你要是不搜怎么下  你怎么知道这个的？

**Comment by wqdl1** [comment]
这个标题也太道德绑架了，你想扯技术伦理，就陪你说说技术伦理。人类之所以技术发展到现在，就是因为知识传播与技术共享，让越来越多的人掌握科技，人类的整体水平才不断发展。
专利和技术保护手段实际上是保护了资本的利益，让世界的财富分配日益加大，贫富差距导致各种发展问题。不知写这个无耻标题的人的脑子是不是被洗了？ 
不管如何，清华的资源能通过这个工具被越多的人所看到，对国家的发展，对科技的发展，都是一个极好的事情。无私分享这个工具的人，没有私心。利国利民，侠之大者！

**Comment by go-bai** [comment]
> 你简直就是在偷换概念了兄弟
> 1、首先官网是免费开放的 而且这里是玩代码的地方 并且下载了我们只适用于学术研究 并不存在倒卖行为 就算有倒卖行为 就跟你是卖刀的 有人从你这里买了刀杀了人 警察会抓你还是抓他？况且作者已经声明仅用于学术研究下载后24小时内删除。
> 2、你所说的知识产权。知识产权他是卖给了出版社 现在出版社限时免费开放，而且我们下载的书只是看并没有对他书中的内容进行修改或者是抨击 所以本身并没有构成侵权
> 3、你所说的盗版的问题 你记得新闻怎么说的吗？所有正版图书免费限时开放 我就不知道你怎么能下的是盗版？
> 4、纯个人立场：你要是不搜怎么下 你怎么知道这个的？

你怕不是不知道有群聊吧，直接都发群里了还不进来看看是什么吗？一群人把人家网站都搞502了，牛🐂

**Comment by go-bai** [comment]
> 这个标题也太道德绑架了，你想扯技术伦理，就陪你说说技术伦理。人类之所以技术发展到现在，就是因为知识传播与技术共享，让越来越多的人掌握科技，人类的整体水平才不断发展。
> 专利和技术保护手段实际上是保护了资本的利益，让世界的财富分配日益加大，贫富差距导致各种发展问题。不知写这个无耻标题的人的脑子是不是被洗了？
> 不管如何，清华的资源能通过这个工具被越多的人所看到，对国家的发展，对科技的发展，都是一个极好的事情。无私分享这个工具的人，没有私心。利国利民，侠之大者！

呦呦呦，用恶意爬虫代码都给人家搞崩了还在这有理了。

**Comment by litengde** [comment]
杠精出场。。。

**Comment by ImwangXM** [comment]
对不起，各位大佬实在是对不起

**Comment by ImwangXM** [comment]
您说让我怎么跟您道歉，呜呜呜~~~

**Comment by Slievery** [comment]
道德绑架呗，首先作者声明了在24小时以内删除。爬虫的滥用和作者有什么关系吗？说到底也就是将重复几百次几千次的单一操作变成机器自动完成呗。吃人血馒头这类标题不是这么用的

**Comment by go-bai** [comment]
作者也不容易，别乱用就行。

**Comment by babyhoo88** [comment]
我作为一个初学者都能爬下来，我不认为作者哪里有错，倒是某些敝帚自珍道貌岸然的伪君子，你倒是分享些东西啊，没本身有什么资格说别人。再说写这个爬虫的不是作者一个人，大家都是相互借鉴而已，作者都写清楚了只作为学术交流。所以不要五十步笑百步。且行且珍惜。

**Comment by xm634634** [comment]
> 我可能觉得你想秀一秀自己的技术，或者是为了“造福”不想花钱的人。但是你明知这是窃取别人的知识产权，破坏计算机系统，还发布这样的程序，实在是有悖于技术伦理。在疫情下，你这样说是吃人血馒头也不为过；即使不是在疫情下，这也属于无良的技术。没有利益相关，我只是觉得，如果一个技术人没有技术伦理，无异于高知识的犯罪分子，更让人愤恨！

**Wiki**：利用他人的不幸，来使自己获利的行为，被称为“吃人血馒头”

**Baidu**：清华大学的前身清华学堂始建于1911年，校名“清华”源于校址“清华园”地名，
是清政府设立的留美预备学校，其建校的资金源于1908年美国退还的部分**庚子赔款**。



如果说限时免费，清华是本着这种心态：
"傻逼们，好东西限时开放啦！赶紧来买清华出版社的书啊！" 
那么确实不幸：人民之不幸、社会之不幸、时代之不幸。
汇聚全国最优秀学子、最好资源的清华，对国人就这副嘴脸？

本来准备筛选几本书，看完了再决定是否买实体书；
看了你的言论，清华出版社的书，一本都不会再买。

**Comment by ntuchenxy** [comment]
爬虫动作本身并没有错，既然是免费阅读，在线看和离线看并无区别，文泉虽然说可能16号结束免费，但也没有说之前的东西就16号后不能再阅读了。当然，技术这东西一旦放出来，就无法避免被人恶意使用以及贩卖爬出来的书，这些人才是真正要被唾骂的。

**Comment by Cybersariel** [comment]
你是什么人，触犯了你的什么利益，让你发表出这样的言论

**Comment by aeof** [comment]
无利益相关，说的确实过了，不喜欢这种行为发表了下而已，散了吧

**Comment by aeof** [comment]
无利益相关，说的确实过了，不喜欢这种行为发表了下而已，散了吧

**Comment by Cybersariel** [comment]
> 无利益相关，说的确实过了，不喜欢这种行为发表了下而已，散了吧

就这么散了？自珍道貌岸然的伪君子，有什么资格说别人？

**Comment by aeof** [comment]
> > 无利益相关，说的确实过了，不喜欢这种行为发表了下而已，散了吧
> 
> 就这么散了？自珍道貌岸然的伪君子，有什么资格说别人？

我发表我个人看法，你有意见？我就是看不惯，就是说下，你还有话说？我没说过我是啥君子，你哪里来的伪君子了？？？？？

**Comment by lovejun277** [comment]
我就想骂人...人家分享点东西怎么了?有钱人还不稀罕电子档~都是买书~我们是穷人.好呆我们有学习的动机~我学点东西,到底是害了国家还是害了你~
