### ISSUE TITLE
抓取数据分享

### ISSUE THREAD

**Issue by kdxcxs** [kajweb/wqxuetang_downloader#23]
我是隔壁[wqDownloader](https://github.com/kdxcxs/wqDownloader)的作者，前两天没发现这个仓库就用自己的方法抓了几本书下来。现在可能服务器扛不住了一直加载不出来，上GitHub再搜就发现了这个仓库。

> 用知识战疫

这是文泉学堂近期免费图书的初衷，但是现在服务器的状态似乎并不乐观，所以如果有人需要的话，我愿意将自己之前下的分享出来。但与文泉学堂一样，疫情结束，我就取消分享。

[OneDrive](https://1drv.ms/u/s!Apfe2uQaXs5djFN2_FTG7wQ59ck6?e=03P4Ue)
[百度云](https://pan.baidu.com/s/1vWmraPb-Inp4nCjoiwU0xQ)

**Comment by Youan** [comment]
建议分享PDF

**Comment by kajweb** [comment]
我先关为敬 ![](https://sticker.weixin.qq.com/htdocs/zh_CN/images/index/register_447d04f.png)
