### ISSUE TITLE
现在需要登陆账号才能免费阅读了

### ISSUE THREAD

**Issue by Anqing-None** [kajweb/wqxuetang_downloader#24]
https://pro-cs-freq.kefutoutiao.com/doc/im/tid56695/QQ%E5%9B%BE%E7%89%8720200204161145_1580808221030_ektn8.png

**Comment by kajweb** [comment]
为啥你的重要通知跟我的重要通知不太一样

**Comment by kajweb** [comment]
样式。文字内容都一样

**Comment by kajweb** [comment]
已修复，请参照patch1修复
