### ISSUE TITLE
下载到一定页数后就不能继续下载了

### ISSUE THREAD

**Issue by Kuoliang-Chung** [kajweb/wqxuetang_downloader#3]
下载到一定页数后，就下载不动了，需要重新启动程序才能下载。能否建立一个检测机制，让程序能自动重启下载？

**Comment by litengde** [comment]
dei，我也这样。

**Comment by Reast1nPeace** [comment]
+1一次只能下载7-8页

**Comment by TheGayhub** [comment]
我也是下着下着就不动了

**Comment by xm634634** [comment]
同样的问题，感觉是jwt的问题
jwt_key = g0NnWdSE8qEjdMD8a1aq12qEYphwErKctvfd3IktWHWiOBpVsgkecur38aBRPn2w

**Comment by litengde** [comment]
> 同样的问题，感觉是jwt的问题
> jwt_key = g0NnWdSE8qEjdMD8a1aq12qEYphwErKctvfd3IktWHWiOBpVsgkecur38aBRPn2w

你的意思是过期了？

**Comment by kajweb** [comment]
我这边也是……
直接打开阅读也很慢……
会不会是用的人多了小水管撑不住……

**Comment by kajweb** [comment]
因为我昨天写的时候下载很丝滑……所以没有写重试。睡醒就出问题了

**Comment by TheGayhub** [comment]
> 因为我昨天写的时候下载很丝滑……所以没有写重试。睡醒就出问题了

咋解决呀

**Comment by xm634634** [comment]
每个人的jwt_key应该是根据cookie和session变化，有时效性的吧

**Comment by litengde** [comment]
> 我这边也是……
> 直接打开阅读也很慢……
> 会不会是用的人多了小水管撑不住……

不会是受不了这么多爬虫的访问吧/?!!!!!!!

**Comment by xm634634** [comment]
> 我这边也是……
> 直接打开阅读也很慢……
> 会不会是用的人多了小水管撑不住……

我觉得是因为大家都用的这个jwt_key，而每个人的jwt_key不可能同时来自多个不同ip访问，所以被ban了。关键是个人怎么获取jwt_key

**Comment by xm634634** [comment]
> > 我这边也是……
> > 直接打开阅读也很慢……
> > 会不会是用的人多了小水管撑不住……
> 
> 不会是受不了这么多爬虫的访问吧/?!!!!!!!

可以正常访问，不能下载，被ban可能性比较大

**Comment by kajweb** [comment]
jwt应该是固定的，刚刚接受了PR改了timeout和重试了。
现在疑似反扒或者是太多下载了网站受不了
毕竟之前网站是收费的，突然这么多免费用户过来

**Comment by xm634634** [comment]
> jwt应该是固定的，刚刚接受了PR改了timeout和重试了。
> 现在疑似反扒或者是太多下载了网站受不了
> 毕竟之前网站是收费的，突然这么多免费用户过来

可以用了，jwt是怎么获取到的，搜了半天没找到解决问题的方法
k=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwIjoxLCJ0IjoxNTgwNzE3MDM1MDAwLCJiIjoiMzIwODQ3MyIsInciOjEwMDAsImsiOiJ7XCJ1XCI6XCJVb1NYSE5DREptND1cIixcImlcIjpcIk41STEwRGNiR0UrY21SLzNMV2VSMFE9PVwiLFwidFwiOlwicm9mQkRwNXlxTlJUbm9IRTk5Q0ZFUT09XCIsXCJiXCI6XCJmTjFrSGt2cExsWT1cIixcIm5cIjpcImM2MXJBQnlycytnPVwifSIsImlhdCI6MTU4MDcxNzAzNX0.mrtUuuLjxIX0BfGDU_L78uyfJ4LakXLfgYwEdWQKAwQ

**Comment by litengde** [comment]
> jwt应该是固定的，刚刚接受了PR改了timeout和重试了。
> 现在疑似反扒或者是太多下载了网站受不了
> 毕竟之前网站是收费的，突然这么多免费用户过来

厉害，是能用了，不过网站悲剧了，我觉得快修复了，慌~

**Comment by litengde** [comment]
咱们要不把时间间隔调大一点把，八成是网站受不了

**Comment by ntuchenxy** [comment]
昨天夜里确实运行很好，今天估计爬的人多了，中途重新下载似乎生成pdf会出错

**Comment by maxiaoan** [comment]
> > jwt应该是固定的，刚刚接受了PR改了timeout和重试了。
> > 现在疑似反扒或者是太多下载了网站受不了
> > 毕竟之前网站是收费的，突然这么多免费用户过来
> 
> 可以用了，jwt是怎么获取到的，搜了半天没找到解决问题的方法
> k=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwIjoxLCJ0IjoxNTgwNzE3MDM1MDAwLCJiIjoiMzIwODQ3MyIsInciOjEwMDAsImsiOiJ7XCJ1XCI6XCJVb1NYSE5DREptND1cIixcImlcIjpcIk41STEwRGNiR0UrY21SLzNMV2VSMFE9PVwiLFwidFwiOlwicm9mQkRwNXlxTlJUbm9IRTk5Q0ZFUT09XCIsXCJiXCI6XCJmTjFrSGt2cExsWT1cIixcIm5cIjpcImM2MXJBQnlycytnPVwifSIsImlhdCI6MTU4MDcxNzAzNX0.mrtUuuLjxIX0BfGDU_L78uyfJ4LakXLfgYwEdWQKAwQ

怎么获取jwt，我修改成自己的的是不是能好一些

**Comment by xm634634** [comment]
> > > jwt应该是固定的，刚刚接受了PR改了timeout和重试了。
> > > 现在疑似反扒或者是太多下载了网站受不了
> > > 毕竟之前网站是收费的，突然这么多免费用户过来
> > 
> > 
> > 可以用了，jwt是怎么获取到的，搜了半天没找到解决问题的方法
> > k=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwIjoxLCJ0IjoxNTgwNzE3MDM1MDAwLCJiIjoiMzIwODQ3MyIsInciOjEwMDAsImsiOiJ7XCJ1XCI6XCJVb1NYSE5DREptND1cIixcImlcIjpcIk41STEwRGNiR0UrY21SLzNMV2VSMFE9PVwiLFwidFwiOlwicm9mQkRwNXlxTlJUbm9IRTk5Q0ZFUT09XCIsXCJiXCI6XCJmTjFrSGt2cExsWT1cIixcIm5cIjpcImM2MXJBQnlycytnPVwifSIsImlhdCI6MTU4MDcxNzAzNX0.mrtUuuLjxIX0BfGDU_L78uyfJ4LakXLfgYwEdWQKAwQ
> 
> 怎么获取jwt，我修改成自己的的是不是能好一些

我也是这想法

**Comment by BillXuce** [comment]
在https://lib-nuanxin.wqxuetang.com/static/read/js/read.v5.3.1.722eb.js 中有一项jwtSecret后面就是

**Comment by BillXuce** [comment]
jwt确实是固定的，不能修改，我看了我的jwt和作者的是一样的，在read.v5.3.1.722eb.js中有一项jwtSecret，我跟作者的对比的一下确实是一样的

**Comment by litengde** [comment]
> jwtSecret

都是一样的

**Comment by xm634634** [comment]
> 在https://lib-nuanxin.wqxuetang.com/static/read/js/read.v5.3.1.722eb.js 中有一项jwtSecret后面就是

好的，谢谢

**Comment by kajweb** [comment]
已修复，有问题麻烦再提新的Issues。
