### ISSUE TITLE
打补丁后提示一个小问题

### ISSUE THREAD

**Issue by ssgemail** [kajweb/wqxuetang_downloader#30]
技术攻防战，精彩！

Traceback (most recent call last):
  File "main.py", line 12, in <module>
    initUrllib();
  File "C:\wqxuetang_downloader-master\utils.py", line 78, in initUrllib
    cookie = http.cookiejar.LWPCookieJar()
NameError: name 'http' is not defined

**Comment by kajweb** [comment]
在utils上面增加 import http.cookiejar

**Comment by ssgemail** [comment]
加了之后，另一个异常

    book = wqxtDownloader( bid );
  File "C:\wqxuetang_downloader-master\wqxtDownloader.py", line 30, in __init__
    self.name = bookInfo['name'];
TypeError: list indices must be integers or slices, not str

**Comment by kajweb** [comment]
这个你是的cookies有问题

**Comment by kajweb** [comment]
我的是26位英文、数字

**Comment by ssgemail** [comment]
![image](https://user-images.githubusercontent.com/10862361/73753318-78c78280-479d-11ea-8327-15d5ce7fc539.png)

**Comment by ssgemail** [comment]
![001](https://user-images.githubusercontent.com/10862361/73753455-b3311f80-479d-11ea-99ce-1670ca9a44a2.png)

**Comment by kajweb** [comment]
bid是否没问题

**Comment by ssgemail** [comment]
bid正确
https://lib-nuanxin.wqxuetang.com/#/Book/3208994

**Comment by litengde** [comment]
C:\Users\liten\Desktop\wqxuetang_downloader-master\cookies.txt
请输入需要下载的bid：2175744
Traceback (most recent call last):
  File "C:\Users\liten\Desktop\wqxuetang_downloader-master\main.py", line 23, in <module>
    book = wqxtDownloader( bid );
  File "C:\Users\liten\Desktop\wqxuetang_downloader-master\wqxtDownloader.py", line 30, in __init__
    self.name = bookInfo['name'];
TypeError: list indices must be integers or slices, not str

我的报错这个

**Comment by kajweb** [comment]
你们登录成功没？需要先登录哇……

**Comment by ssgemail** [comment]
成功了，要不然无法获取PHPSESSID={vj30d4gnfqunk2lrbd9b6rc31s}

**Comment by kajweb** [comment]
https://lib-nuanxin.wqxuetang.com/v1/read/initread?bid=2175744
直接在浏览器打开，看看能不能获得数据

**Comment by ssgemail** [comment]
可以
{"data":{"canread":1,"upperlimit":1,"bid":"2175744","toshelf":null,"name":"计算机网络基础","title":"《计算机网络基础》 刘勇 邹广慧 【正版电子纸书阅读_PDF下载】- 书问","pages":"311","coverurl":"https://bookask-cover.oss-cn-beijing.aliyuncs.com/c/2/175/2175744/2175744.jpg!b","volume_list":[],"ismultivolumed":"0","lastpage":1,"last_volume":1,"price":"39.00","sellprice":"25.35","canreadpages":"311","uid":"1163643","textbook":"0","paperlowprice":"26.90","paperurl":"http://product.dangdang.com/24011520.html?_ddclickunion=P-327429|ad_type=10|sys_id=1#dd_refer="},"errcode":0,"errmsg":"success"}

**Comment by litengde** [comment]
{“ data”：{“ canread”：1，“ upperlimit”：1，“ bid”：“ 2175744”，“ toshelf”：null，“ name”：“计算机网络基础”，“ title”：“《计算机网络》基础》刘勇邹广慧【正版电子纸书阅读_PDF下载】-书问“，”页面“：” 311“，” coverurl“：” https://bookask-cover.oss-cn-beijing.aliyuncs.com /c/2/175/2175744/2175744.jpg!b","volume_list":[],"multivolumed":"0","lastpage":"10","last_volume":"1","price“ ：“ 39.00”，“卖价”：“ 25.35”，“ canreadpages”：“ 311”，“ uid”：“ 1143990”，“教科书”：“ 0”，“ paperlowprice”：“ 26.90”，“ paperurl”：“ http://product.dangdang.com/24011520。html？_ddclickunion = P-327429 | ad_type = 10 | sys_id = 1＃dd_refer =“}，” errcode“：0，” errmsg“：”成功“}

**Comment by litengde** [comment]
应该就是不会打补丁。。。我也是

**Comment by kajweb** [comment]
格式是这样的
Set-Cookie3: PHPSESSID=XXXXXXXXXXXXXXXXXX; path="/"; domain=.wqxuetang.com; path_spec; expires="0"; version=0

**Comment by kajweb** [comment]
把你的main.py的代码发上来

**Comment by litengde** [comment]
#!/usr/bin/python3
# -*- coding: UTF-8 -*- 

from utils import *
from wqxtDownloader import *;

# 初始化全局变量
globalvar_init();
# 初始化urllib
setCookiesFile(os.getcwd()+"\\cookies.txt");
initUrllib();
# 删除initUrllibNoCookies();
# 初始化logging


if __name__ == '__main__':
	# usage: python3 main.py <book_id> <start> <end>
	loggingLevel("INFO");
	LSArg = len(sys.argv);
	if LSArg==1:
		bid = input("请输入需要下载的bid：");
		book = wqxtDownloader( bid );
		book.start();
	else:
		bid = sys.argv[1];
		book = wqxtDownloader( bid );
		book.start( *(int(x) for x in sys.argv[2:]) );

**Comment by ssgemail** [comment]
哦，找到原因了
PHPSESSID={vj30d4gnfqunk2lrbd9b6rc31s}
需要变为
PHPSESSID=vj30d4gnfqunk2lrbd9b6rc31s

**Comment by ssgemail** [comment]
感谢kajweb

**Comment by litengde** [comment]
我的也好了

**Comment by Kuoliang-Chung** [comment]
谢谢大佬kajweb
