### ISSUE TITLE
现在不能用了？不过还是资瓷

### ISSUE THREAD

**Issue by e0r** [kajweb/wqxuetang_downloader#31]
俺来上传一个自主研发独立知识产权刚刚申请好专利的版本
https://github.com/e0r/wqxuetang_anjian
基于按键精灵，反正没真正的python爬虫快就是了，正在学习爬虫技术，

**Comment by kajweb** [comment]
能用

**Comment by e0r** [comment]
> 能用

没看懂怎么下载你的程序？

**Comment by kajweb** [comment]
用git reset下载旧版本，然后根据新版本的指引修改代码
