### ISSUE TITLE
心态下楼主，顺便问下怎么更新补丁呀？纯属小白

### ISSUE THREAD

**Issue by chendaojjj** [kajweb/wqxuetang_downloader#32]
碎碎念，都是穷人，免费下了基本好书，何必上纲上线，心态下楼主~~
PS：能指导下载python中打入patch补丁？？完全找不大资料呀，commit ad0c71480c4eeaf338d09492237ed70e3d28d0be 直接输入直接报错，感谢

**Comment by kajweb** [comment]
- 学git reset
- 手动替换代码[手动狗头]
