### ISSUE TITLE
http解决后，请问怎么解决name的问题？：name 'http' is not defined

### ISSUE THREAD

**Issue by ynlsg** [kajweb/wqxuetang_downloader#37]
C:\Users\ynlsg\wqxuetang_downloader10>python main.py
C:\Users\ynlsg\wqxuetang_downloader10\cookies.txt
Traceback (most recent call last):
  File "main.py", line 13, in <module>
    initUrllib();
  File "C:\Users\ynlsg\wqxuetang_downloader10\utils.py", line 17, in initUrllib
    cookie = http.cookiejar.LWPCookieJar()
NameError: name 'http' is not defined

**Comment by ynlsg** [comment]
问题看错了，还是http的问题。。

**Comment by kajweb** [comment]
utils.py 增加 import http.cookiejar 即可。
