### ISSUE TITLE
按照patch1和2修改了代码,并且也修改了PHPSESSID,但是仍然提示需要登录

### ISSUE THREAD

**Issue by yellowredhh** [kajweb/wqxuetang_downloader#38]
输出代码中的data信息,显示data: {"data":[],"errcode":3001,"errmsg":"请先登录"}

**Comment by kajweb** [comment]
PHPSESSID错了

**Comment by yellowredhh** [comment]
> PHPSESSID错了

好吧,忘记把大括号去掉了,现在出现新问题了,一直报urllib.error.HTTPError: HTTP Error 504: Gateway Time-out

**Comment by kajweb** [comment]
504我们没出现过。估计是你网络问题。
