### ISSUE TITLE
【报错】 AttributeError: 'wqxtDownloader' object has no attribute 'isLogin'

### ISSUE THREAD

**Issue by derryck404** [kajweb/wqxuetang_downloader#45]
已按照步骤，登录并修改PHPSESSID值，仍出现登录错误，如下：
  AttributeError: 'wqxtDownloader' object has no attribute 'isLogin'

**Comment by kajweb** [comment]
patch3漏了一步

**Comment by kajweb** [comment]
写错函数名了
wqxtDownloader.py (Line:249)
由getLogin修改为isLogin
