### ISSUE TITLE
【报错】NameError: name 'sleepTime' is not defined

### ISSUE THREAD

**Issue by derryck404** [kajweb/wqxuetang_downloader#47]
419页只下了14页，出现以下错误：
**urllib.error.HTTPError: HTTP Error 503: Service Temporarily Unavailable** 【可能是网络原因】

**NameError: name 'sleepTime' is not defined**
"wqxtDownloader.py", line 186, in start
    logging.error("{} 发生了严重错误，暂停s秒 第{}页({}/{}) 正在重试第{}次".format( str(bid), str(sleepTime), page, str(downloadTimes), str(countNum), str(Errortimes)));

**Comment by kajweb** [comment]
请使用git pull更新到最新版本

**Comment by kajweb** [comment]
最新版对error.URLError进行了处理，大部分503错误可以捕获并处理。
