### ISSUE TITLE
请问更新版下载书时，提示登陆错误怎么解决

### ISSUE THREAD

**Issue by a2448116274** [kajweb/wqxuetang_downloader#48]
麻烦问下我是用的更新到最新版本的，下载时提示登陆错误，程序异常退出：
C:\Users\Administrator\Desktop\wqxuetang_downloader-master>python main.py 3199490
2020-02-06 14:18:52,394 [ERROR] 登录错误，程序异常退出。
请问该如何解决？

**Comment by iMicroSoftever** [comment]
我也是，之前没更新前提示与服务器断开连接，是不是被封了啊，怎么办

**Comment by BillXuce** [comment]
> 麻烦问下我是用的更新到最新版本的，下载时提示登陆错误，程序异常退出：
> C:\Users\Administrator\Desktop\wqxuetang_downloader-master>python main.py 3199490
> 2020-02-06 14:18:52,394 [ERROR] 登录错误，程序异常退出。
> 请问该如何解决？

你是否在cookies.txt中替换了自己登录后获取到的cookies呢？

**Comment by a2448116274** [comment]
替换了。我刚又特意去确认了一下，替换了仍不行

**Comment by a2448116274** [comment]
问题解决了，开始用谷歌浏览器获取的cookies，替换后报错，我换成win10自带的浏览器获取cookies替换后成功

**Comment by kajweb** [comment]
获取的cookies不对或者失效。
