### ISSUE TITLE
登录不了

### ISSUE THREAD

**Issue by iMicroSoftever** [kajweb/wqxuetang_downloader#49]
2020-02-06 14:58:55,814 [ERROR] 登录错误，程序异常退出

**Comment by iMicroSoftever** [comment]
这是不是被封了

**Comment by iMicroSoftever** [comment]
解决了，换一个cookies就好了哈哈

**Comment by iMicroSoftever** [comment]
下载了几页又提示这个了
http.client.RemoteDisconnected: Remote end closed connection without response

**Comment by iMicroSoftever** [comment]
断开网络连接重新连上又好了哈哈

**Comment by lovejun277** [comment]
怎么换cookise ?我是小白

**Comment by kajweb** [comment]
> 怎么换cookise ?我是小白

请参考[Wiki](https://github.com/kajweb/wqxuetang_downloader/wiki/安装方法)

**Comment by kajweb** [comment]
> 下载了几页又提示这个了
> http.client.RemoteDisconnected: Remote end closed connection without response

http.client.RemoteDisconnected情况多吗？不多就不管了
