### ISSUE TITLE
希望支持输入多个待下载bid，以“，”分割

### ISSUE THREAD

**Issue by coloraven** [kajweb/wqxuetang_downloader#50]
因为本身下载需要模拟人在阅读，耗时很长，所以最好能支持多个待下载bid，感谢大佬。

**Comment by iMicroSoftever** [comment]
支持了啊更新了

**Comment by kajweb** [comment]
[多本书下载](https://github.com/kajweb/wqxuetang_downloader/wiki/多本书下载)

不过最新版被移除了,变成在main.py加参数了。

**Comment by coloraven** [comment]
> [多本书下载](https://github.com/kajweb/wqxuetang_downloader/wiki/%E5%A4%9A%E6%9C%AC%E4%B9%A6%E4%B8%8B%E8%BD%BD)
> 
> 不过最新版被移除了,变成在main.py加参数了。

是我自己没仔细看wiki。。。不过在main的“输入提示”里将多本下载的格式放进去更贴心。
