### ISSUE TITLE
main报错了

### ISSUE THREAD

**Issue by litengde** [kajweb/wqxuetang_downloader#54]
Traceback (most recent call last):
  File "C:\Users\liten\Desktop\wqxuetang_downloader\main.py", line 33, in <module>
    if opts[0][0] in ['-h','--help']:
IndexError: list index out of range

**Comment by kajweb** [comment]
这个是刚刚pr的，wiki还没修改
移除了main_mult.py，修改参数格式，支持多个图书下载；改进报错机制；pdf支持指定页码

**Comment by kajweb** [comment]
@BillXuce 同学修改的，等会儿我看下在吗，再将wiki改一下。

**Comment by litengde** [comment]
嗯呐，我就是吃螃蟹的，我不着急用

**Comment by kajweb** [comment]
你有空可以帮忙维护一下Wiki呀

**Comment by litengde** [comment]
我，不会玩这个。。。

**Comment by litengde** [comment]
我刚刚pull 最新的这个，报错，我搞不懂怎么用来着

**Comment by kajweb** [comment]
我也不会……我都还没看直接就pr进去了、
用`python main.py -h`可以看到说明

**Comment by litengde** [comment]
C:\Users\liten>D:\wqxuetang_downloader-master\main.py -h
Traceback (most recent call last):
  File "D:\wqxuetang_downloader-master\main.py", line 13, in <module>
    initUrllib();
  File "D:\wqxuetang_downloader-master\utils.py", line 53, in initUrllib
    cookie.load( cookies_file, ignore_discard=True, ignore_expires=True)
  File "C:\Users\liten\AppData\Local\Programs\Python\Python38\lib\http\cookiejar.py", line 1798, in load
    with open(filename) as f:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\liten\\cookies.txt'

**Comment by litengde** [comment]
报错这个，我的cookies文件也弄好了，不行

**Comment by kajweb** [comment]
No such file or directory: 'C:\Users\liten\cookies.txt'

**Comment by kajweb** [comment]
这个真的是你没有认真看文档的问题。

**Comment by litengde** [comment]
> No such file or directory: 'C:\Users\liten\cookies.txt'

懂了，还得把cookies放在这个位置

**Comment by litengde** [comment]
不能和这个放在同一个目录

**Comment by kajweb** [comment]
我知道了，那个兄弟把cookies.txt文件删除了。。。

**Comment by kajweb** [comment]
你看看目录有没有cookies.txt文件

**Comment by litengde** [comment]
和这个文件在同一目录不管用，必须在我的用户目录下有这个cookies才可以用
No such file or directory: 'C:\Users\liten\cookies.txt'

**Comment by kajweb** [comment]
C:\Users\liten>D:\wqxuetang_downloader-master\main.py -h
因为你不是切换到程序目录执行的。。。

**Comment by kajweb** [comment]
emmm，算了，问题不大。你自己可以解决，。

**Comment by litengde** [comment]
emmmm~

**Comment by litengde** [comment]
其实说实在的，对我来说，这个版本不如你上一版好用，直接双击就能运行

**Comment by BillXuce** [comment]
稍等我去改一下wiki

**Comment by litengde** [comment]
> 等我去改一下wiki

大。。大佬

**Comment by BillXuce** [comment]
> 其实说实在的，对我来说，这个版本不如你上一版好用，直接双击就能运行

我的锅，我当时想着给无参数运行放回去了，但是我给忘了，我的锅我的锅，一会我处理一下

**Comment by kajweb** [comment]
> 稍等我去改一下wiki

你应该有权限修改Wiki吧

**Comment by BillXuce** [comment]
> > 稍等我去改一下wiki
> 
> 你应该有权限修改Wiki吧

在改了

**Comment by litengde** [comment]
> > 其实说实在的，对我来说，这个版本不如你上一版好用，直接双击就能运行
> 
> 我的锅，我当时想着给无参数运行放回去了，但是我给忘了，我的锅我的锅，一会我处理一下

我没别的意思，我，就是随便说一下我我的使用感受<害怕>

**Comment by BillXuce** [comment]
> > > 其实说实在的，对我来说，这个版本不如你上一版好用，直接双击就能运行
> > 
> > 
> > 我的锅，我当时想着给无参数运行放回去了，但是我给忘了，我的锅我的锅，一会我处理一下
> 
> 我没别的意思，我，就是随便说一下我我的使用感受<害怕>

嗨，这没啥，这就是issues的意义嘛

**Comment by litengde** [comment]
> > > > 其实说实在的，对我来说，这个版本不如你上一版好用，直接双击就能运行
> > > 
> > > 
> > > 我的锅，我当时想着给无参数运行放回去了，但是我给忘了，我的锅我的锅，一会我处理一下
> > 
> > 
> > 我没别的意思，我，就是随便说一下我我的使用感受<害怕>
> 
> 嗨，这没啥，这就是issues的意义嘛

不愧是大佬（滑稽
