### ISSUE TITLE
批量下载后会把几本书都输出到一个pdf文件里面

### ISSUE THREAD

**Issue by darkness112** [kajweb/wqxuetang_downloader#56]
D:\Anaconda3\python.exe D:/python/work/book/main_mult.py
请输入需要下载的bid(以间隔)：3208838 3208806 3209047 3206842 3207371
![image](https://user-images.githubusercontent.com/60617447/73939098-acccb000-4923-11ea-850b-ffced071d378.png)

**Comment by litengde** [comment]
这有啥问题嘛？

**Comment by darkness112** [comment]
每往后面一本书的pdf包含了前面几本的内容

**Comment by litengde** [comment]
这是个bug，我刚发现

**Comment by BillXuce** [comment]
最新的commit(d14a6769ba163fcb44e15c681ab6c35d4552b18e)已解决
