### ISSUE TITLE
PDF生成BUG？

### ISSUE THREAD

**Issue by lsz52469803** [kajweb/wqxuetang_downloader#57]
![image](https://user-images.githubusercontent.com/60741043/73944710-02a65580-492e-11ea-907f-95058fdaf5fd.png)
其他书下完能生成PDF，暂时就这本生成出现错误！不知是啥原因望指点！

**Comment by BillXuce** [comment]
因为这本图书书名里的CAD/CAM有个`/`，导致识别成了另外一个文件夹。恭喜你中枪了

**Comment by lsz52469803** [comment]
只能等死？大神有解法吗？

**Comment by BillXuce** [comment]
目前最新commit已解决 4b537a251ea6ff617577606badbee9d256b37353

**Comment by lsz52469803** [comment]
谢谢大神！请受小弟一拜！
