### ISSUE TITLE
一直获取到了失败的图片 重试次数过多

### ISSUE THREAD

**Issue by zhuting233** [kajweb/wqxuetang_downloader#61]

**Comment by lovejun277** [comment]
是的 我这里也是 正常打开也 不显示~不知道是不是清华瘪三 又在弄什么幺蛾子~




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"cao"<notifications@github.com&gt;;
发送时间:&nbsp;2020年2月7日(星期五) 凌晨1:14
收件人:&nbsp;"kajweb/wqxuetang_downloader"<wqxuetang_downloader@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[kajweb/wqxuetang_downloader] 一直获取到了失败的图片 重试次数过多 (#61)

**Comment by kajweb** [comment]
正常打开也不显示，疑似有进一步操作或者服务器崩了

**Comment by HoeYeungHo** [comment]
我觉得是进一步操作了 用了代理 换了几个IP在官网上面还是显示正在加载

**Comment by kajweb** [comment]
有点奇怪，就前2、3页刚开始加载不行，。后面的加载又可以了。，尽管其变。

**Comment by zky001** [comment]
我这里也是  一直错误

**Comment by litengde** [comment]
我的也。不行啦，从昨晚12点09就开始了

**Comment by qiuyu2020** [comment]
刚才测试了一下，同样的问题。现在通过浏览器随便打开一个，也浏览不出来了

**Comment by zky001** [comment]
开了代理也还是  ss  vpn这些都试了

**Comment by yellowredhh** [comment]
都出现问题了啊,我从昨天下午就有了

**Comment by qiuyu2020** [comment]
貌似没问题了

**Comment by litengde** [comment]
really?

**Comment by zhuting233** [comment]
好像没问题了

**Comment by lovejun277** [comment]
我这里正常网页阅读都不打不开了 卡加载了 不知道是服务器对我做了什么没?




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "cao"<notifications@github.com&gt;; 
发送时间: 2020年2月7日(星期五) 中午11:08
收件人: "kajweb/wqxuetang_downloader"<wqxuetang_downloader@noreply.github.com&gt;; 
抄送: "世上疼我的去了"<ouyijun@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [kajweb/wqxuetang_downloader] 一直获取到了失败的图片 重试次数过多 (#61)




好像没问题了
 
&mdash;

**Comment by zky001** [comment]
可以了
