### ISSUE TITLE
为p添加目录

### ISSUE THREAD

**Issue by Penghaiku** [kajweb/wqxuetang_downloader#63]
油猴脚本作者已经制成为pdf添加目录的.exe文件，https://github.com/Kevin0z0/wenquan-pdf-download，如果能够制成批量pdf添加目录就好了，关键在于找到不同书本的书名和cookie

**Comment by BillXuce** [comment]
没太明白你的意思，当前版本已经支持在pdf中生成目录了

**Comment by Penghaiku** [comment]
好的，但是用脚本下载的电子书没有目录

**Comment by lovejun277** [comment]
服你 太奢侈~




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Roger"<notifications@github.com&gt;; 
发送时间: 2020年2月7日(星期五) 中午12:47
收件人: "kajweb/wqxuetang_downloader"<wqxuetang_downloader@noreply.github.com&gt;; 
抄送: "Subscribed"<subscribed@noreply.github.com&gt;; 
主题: Re: [kajweb/wqxuetang_downloader] 为p添加目录 (#63)




好的，但是用脚本下载的电子书没有目录
 
&mdash;

**Comment by BillXuce** [comment]
额pdf中不是已经存在书签了吗，可以作为目录用的啊，难道你下载出来的pdf是没有书签的版本吗

**Comment by kajweb** [comment]
您好，本脚本很早前已经支持自动插入目录。请查看版本或检查是否操作步骤有误。
