### ISSUE TITLE
悦读下载报错

### ISSUE THREAD

**Issue by derryck404** [kajweb/wqxuetang_downloader#64]
C:\Users\Downloads\Compressed\Release>ebookDown.exe 68259052
开始下载:《知识图谱：方法、实践与应用》.pdf

未处理的异常:  System.Net.WebException: 远程服务器返回错误: (404) 未找到。
   在 System.Net.HttpWebRequest.GetResponse()
   在 ydDownloader.Program.DownloadFile(String URL, String filename)
   在 ydDownloader.Program.Main(String[] args)

**Comment by kajweb** [comment]
2020/02/06 23:14 
网站更新，悦读下载器已失效

网站更新了秘钥加密方式为rsa，顺便把js也混淆了一下。

**Comment by kajweb** [comment]
之前悦读版本作者已经不再更新，正在测试其他开源项目。
等找到能用开源项目将更新。

**Comment by lovejun277** [comment]
再过几天免费就要结束了 




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "kajweb"<notifications@github.com&gt;; 
发送时间: 2020年2月9日(星期天) 晚上9:26
收件人: "kajweb/wqxuetang_downloader"<wqxuetang_downloader@noreply.github.com&gt;; 
抄送: "Subscribed"<subscribed@noreply.github.com&gt;; 
主题: Re: [kajweb/wqxuetang_downloader] 悦读下载报错 (#64)




之前悦读版本作者已经不再更新，正在测试其他开源项目。
 等找到能用开源项目将更新。
 
&mdash;
