### ISSUE TITLE
报错 悦读 感觉网站是不是换了加密

### ISSUE THREAD

**Issue by motoyeart** [kajweb/wqxuetang_downloader#65]
正在下载:[100%]17368019/1736801968019
未处理的异常:  System.Security.Cryptography.CryptographicException: 要解密的数据的长度无效。
   在 System.Security.Cryptography.RijndaelManagedTransform.TransformFinalBlock(Byte[] inputBuffer, Int32 inputOffset, Int32 inputCount)
   在 ydDownloader.Program.decrypt_book(Byte[] toEncryptArray, String key)
   在 ydDownloader.Program.Main(String[] args)

一到百分百就崩了，是不是解密环节出了问题。

**Comment by plybb** [comment]
悦读升级了加密方式，需要大咖修改一下脚本代码

**Comment by kajweb** [comment]
2020/02/06 23:14 
网站更新，悦读下载器已失效

网站更新了秘钥加密方式为rsa，顺便把js也混淆了一下。

**Comment by waynevan** [comment]
系统正在升级，等会再试试吧
因访问流量过大，系统暂停免费使用以便进行升级。稍后会正常开放使用，给您带来的不便请谅解！

**Comment by kajweb** [comment]
之前悦读版本作者已经不再更新，正在测试其他开源项目。
等找到能用开源项目将更新。

**Comment by waynevan** [comment]
https://github.com/sqlsec/keledge_pdf
