### ISSUE TITLE
下载过程中又出问题了

### ISSUE THREAD

**Issue by TheGayhub** [kajweb/wqxuetang_downloader#7]
```cpp
2020-02-03 16:51:02,041 [INFO] 下载成功 第149页(149/357)
2020-02-03 16:51:04,126 [INFO] 下载成功 第150页(150/357)
2020-02-03 16:51:06,002 [INFO] 下载成功 第151页(151/357)
2020-02-03 16:51:07,436 [INFO] 下载成功 第152页(152/357)
2020-02-03 16:51:08,870 [INFO] 下载成功 第153页(153/357)
2020-02-03 16:51:10,444 [INFO] 下载成功 第154页(154/357)
2020-02-03 16:51:12,315 [INFO] 下载成功 第155页(155/357)
Traceback (most recent call last):
  File "E:\Python37\lib\urllib\request.py", line 1317, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "E:\Python37\lib\http\client.py", line 1229, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "E:\Python37\lib\http\client.py", line 1275, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "E:\Python37\lib\http\client.py", line 1224, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "E:\Python37\lib\http\client.py", line 1016, in _send_output
    self.send(msg)
  File "E:\Python37\lib\http\client.py", line 956, in send
    self.connect()
  File "E:\Python37\lib\http\client.py", line 1384, in connect
    super().connect()
  File "E:\Python37\lib\http\client.py", line 932, in connect
    self._tunnel()
  File "E:\Python37\lib\http\client.py", line 906, in _tunnel
    (version, code, message) = response._read_status()
  File "E:\Python37\lib\http\client.py", line 257, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "E:\Python37\lib\socket.py", line 589, in readinto
    return self._sock.recv_into(b)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 20, in <module>
    book.start( *(int(x) for x in sys.argv[2:]) );
  File "D:\Other\wqxuetang_downloader-master\wqxtDownloader.py", line 144, in start
    downloadPage = self.downloadImage( url, path );
  File "D:\Other\wqxuetang_downloader-master\wqxtDownloader.py", line 182, in downloadImage
    request = curl.request.urlopen(requestPer, timeout=10);
  File "E:\Python37\lib\urllib\request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "E:\Python37\lib\urllib\request.py", line 525, in open
    response = self._open(req, data)
  File "E:\Python37\lib\urllib\request.py", line 543, in _open
    '_open', req)
  File "E:\Python37\lib\urllib\request.py", line 503, in _call_chain
    result = func(*args)
  File "E:\Python37\lib\urllib\request.py", line 1360, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "E:\Python37\lib\urllib\request.py", line 1319, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error timed out>
```

**Comment by kajweb** [comment]
访问频率过快，被banIP了。过半个小时再试，增大wqxtDownloader.py里面的timeSleep时间

**Comment by litengde** [comment]
> ```c++
> 2020-02-03 16:51:02,041 [INFO] 下载成功 第149页(149/357)
> 2020-02-03 16:51:04,126 [INFO] 下载成功 第150页(150/357)
> 2020-02-03 16:51:06,002 [INFO] 下载成功 第151页(151/357)
> 2020-02-03 16:51:07,436 [INFO] 下载成功 第152页(152/357)
> 2020-02-03 16:51:08,870 [INFO] 下载成功 第153页(153/357)
> 2020-02-03 16:51:10,444 [INFO] 下载成功 第154页(154/357)
> 2020-02-03 16:51:12,315 [INFO] 下载成功 第155页(155/357)
> Traceback (most recent call last):
>   File "E:\Python37\lib\urllib\request.py", line 1317, in do_open
>     encode_chunked=req.has_header('Transfer-encoding'))
>   File "E:\Python37\lib\http\client.py", line 1229, in request
>     self._send_request(method, url, body, headers, encode_chunked)
>   File "E:\Python37\lib\http\client.py", line 1275, in _send_request
>     self.endheaders(body, encode_chunked=encode_chunked)
>   File "E:\Python37\lib\http\client.py", line 1224, in endheaders
>     self._send_output(message_body, encode_chunked=encode_chunked)
>   File "E:\Python37\lib\http\client.py", line 1016, in _send_output
>     self.send(msg)
>   File "E:\Python37\lib\http\client.py", line 956, in send
>     self.connect()
>   File "E:\Python37\lib\http\client.py", line 1384, in connect
>     super().connect()
>   File "E:\Python37\lib\http\client.py", line 932, in connect
>     self._tunnel()
>   File "E:\Python37\lib\http\client.py", line 906, in _tunnel
>     (version, code, message) = response._read_status()
>   File "E:\Python37\lib\http\client.py", line 257, in _read_status
>     line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
>   File "E:\Python37\lib\socket.py", line 589, in readinto
>     return self._sock.recv_into(b)
> socket.timeout: timed out
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "main.py", line 20, in <module>
>     book.start( *(int(x) for x in sys.argv[2:]) );
>   File "D:\Other\wqxuetang_downloader-master\wqxtDownloader.py", line 144, in start
>     downloadPage = self.downloadImage( url, path );
>   File "D:\Other\wqxuetang_downloader-master\wqxtDownloader.py", line 182, in downloadImage
>     request = curl.request.urlopen(requestPer, timeout=10);
>   File "E:\Python37\lib\urllib\request.py", line 222, in urlopen
>     return opener.open(url, data, timeout)
>   File "E:\Python37\lib\urllib\request.py", line 525, in open
>     response = self._open(req, data)
>   File "E:\Python37\lib\urllib\request.py", line 543, in _open
>     '_open', req)
>   File "E:\Python37\lib\urllib\request.py", line 503, in _call_chain
>     result = func(*args)
>   File "E:\Python37\lib\urllib\request.py", line 1360, in https_open
>     context=self._context, check_hostname=self._check_hostname)
>   File "E:\Python37\lib\urllib\request.py", line 1319, in do_open
>     raise URLError(err)
> urllib.error.URLError: <urlopen error timed out>
> ```

怎么样了？

**Comment by TheGayhub** [comment]
> > ```c++
> > 2020-02-03 16:51:02,041 [INFO] 下载成功 第149页(149/357)
> > 2020-02-03 16:51:04,126 [INFO] 下载成功 第150页(150/357)
> > 2020-02-03 16:51:06,002 [INFO] 下载成功 第151页(151/357)
> > 2020-02-03 16:51:07,436 [INFO] 下载成功 第152页(152/357)
> > 2020-02-03 16:51:08,870 [INFO] 下载成功 第153页(153/357)
> > 2020-02-03 16:51:10,444 [INFO] 下载成功 第154页(154/357)
> > 2020-02-03 16:51:12,315 [INFO] 下载成功 第155页(155/357)
> > Traceback (most recent call last):
> >   File "E:\Python37\lib\urllib\request.py", line 1317, in do_open
> >     encode_chunked=req.has_header('Transfer-encoding'))
> >   File "E:\Python37\lib\http\client.py", line 1229, in request
> >     self._send_request(method, url, body, headers, encode_chunked)
> >   File "E:\Python37\lib\http\client.py", line 1275, in _send_request
> >     self.endheaders(body, encode_chunked=encode_chunked)
> >   File "E:\Python37\lib\http\client.py", line 1224, in endheaders
> >     self._send_output(message_body, encode_chunked=encode_chunked)
> >   File "E:\Python37\lib\http\client.py", line 1016, in _send_output
> >     self.send(msg)
> >   File "E:\Python37\lib\http\client.py", line 956, in send
> >     self.connect()
> >   File "E:\Python37\lib\http\client.py", line 1384, in connect
> >     super().connect()
> >   File "E:\Python37\lib\http\client.py", line 932, in connect
> >     self._tunnel()
> >   File "E:\Python37\lib\http\client.py", line 906, in _tunnel
> >     (version, code, message) = response._read_status()
> >   File "E:\Python37\lib\http\client.py", line 257, in _read_status
> >     line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
> >   File "E:\Python37\lib\socket.py", line 589, in readinto
> >     return self._sock.recv_into(b)
> > socket.timeout: timed out
> > 
> > During handling of the above exception, another exception occurred:
> > 
> > Traceback (most recent call last):
> >   File "main.py", line 20, in <module>
> >     book.start( *(int(x) for x in sys.argv[2:]) );
> >   File "D:\Other\wqxuetang_downloader-master\wqxtDownloader.py", line 144, in start
> >     downloadPage = self.downloadImage( url, path );
> >   File "D:\Other\wqxuetang_downloader-master\wqxtDownloader.py", line 182, in downloadImage
> >     request = curl.request.urlopen(requestPer, timeout=10);
> >   File "E:\Python37\lib\urllib\request.py", line 222, in urlopen
> >     return opener.open(url, data, timeout)
> >   File "E:\Python37\lib\urllib\request.py", line 525, in open
> >     response = self._open(req, data)
> >   File "E:\Python37\lib\urllib\request.py", line 543, in _open
> >     '_open', req)
> >   File "E:\Python37\lib\urllib\request.py", line 503, in _call_chain
> >     result = func(*args)
> >   File "E:\Python37\lib\urllib\request.py", line 1360, in https_open
> >     context=self._context, check_hostname=self._check_hostname)
> >   File "E:\Python37\lib\urllib\request.py", line 1319, in do_open
> >     raise URLError(err)
> > urllib.error.URLError: <urlopen error timed out>
> > ```
> 
> 怎么样了？

我正在下载

**Comment by TheGayhub** [comment]
> 访问频率过快，被banIP了。过半个小时再试，增大wqxtDownloader.py里面的timeSleep时间

还是不行

**Comment by TheGayhub** [comment]
> 访问频率过快，被banIP了。过半个小时再试，增大wqxtDownloader.py里面的timeSleep时间

```cpp
2020-02-03 20:22:29,730 [INFO] 3209109下载成功 第34页(34/357) 随机8.5s
2020-02-03 20:22:39,357 [INFO] 3209109下载成功 第35页(35/357) 随机7.6s
Traceback (most recent call last):
  File "main.py", line 20, in <module>
    book.start( *(int(x) for x in sys.argv[2:]) );
  File "D:\Other\wqxuetang_downloader-master\wqxtDownloader.py", line 151, in start
    downloadPage = self.downloadImage( url, path );
  File "D:\Other\wqxuetang_downloader-master\wqxtDownloader.py", line 197, in downloadImage
    request = curl.request.urlopen(requestPer, timeout=10);
  File "E:\Python37\lib\urllib\request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "E:\Python37\lib\urllib\request.py", line 531, in open
    response = meth(req, response)
  File "E:\Python37\lib\urllib\request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "E:\Python37\lib\urllib\request.py", line 569, in error
    return self._call_chain(*args)
  File "E:\Python37\lib\urllib\request.py", line 503, in _call_chain
    result = func(*args)
  File "E:\Python37\lib\urllib\request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 500: Internal Server Error
```

**Comment by kajweb** [comment]
你是最新的？

**Comment by litengde** [comment]
刚刚人家的服务器都崩了，正常访问都是服务器错误，咱们该慢点了~~hahaha

**Comment by TheGayhub** [comment]
> 你是最新的？
是的

**Comment by TheGayhub** [comment]
> 你是最新的？

是的

**Comment by kajweb** [comment]
缓一缓，崩了

**Comment by litengde** [comment]
x现在下载没问题了，是不是最后生成pdf的时候出bug了？

**Comment by TheGayhub** [comment]
> x现在下载没问题了，是不是最后生成pdf的时候出bug了？

你下载没问题吗

**Comment by litengde** [comment]
> > x现在下载没问题了，是不是最后生成pdf的时候出bug了？
> 
> 你下载没问题吗

没问题啊，就是有点无效图片
