### ISSUE TITLE
2020/02/09 11:37报错

### ISSUE THREAD

**Issue by ijlsqt** [kajweb/wqxuetang_downloader#70]
2020/02/09 11:37报错，请大神调试代码呀。

**Comment by pcbcos** [comment]
同报错

**Comment by iMicroSoftever** [comment]
有滑块了，只能等更新了

**Comment by ssgemail** [comment]
Traceback (most recent call last):
  File "main.py", line 66, in <module>
    parseMultBid(books)
  File "main.py", line 25, in parseMultBid
    book.start([]);
  File "C:\wqxuetang_downloader-master\wqxtDownloader.py", line 192, in start
    raise TooManyRetry;
wqxtDownloader.TooManyRetry: 重试次数超出设定次数

**Comment by BillXuce** [comment]
这种情况一般在下载多长时间之后出现？

**Comment by pcbcos** [comment]
@BillXuce 就今天刚刚出现的，今天前一直正常

**Comment by BillXuce** [comment]
> @BillXuce 就今天刚刚出现的，今天前一直正常

我这边才开始下了20多页但是一直都没有出现问题

**Comment by pcbcos** [comment]
@BillXuce 现在又好了，可能是服务器的问题

**Comment by BillXuce** [comment]
#67  我的最新回复看一下
