### ISSUE TITLE
测试可知平台可以弯道超车下载悦读平台的电子书 有大佬要来完善脚本吗

### ISSUE THREAD

**Issue by sqlsec** [kajweb/wqxuetang_downloader#71]
https://www.sqlsec.com/2020/02/keledge.html

**Comment by kajweb** [comment]
https://github.com/sqlsec/keledge_pdf

你自己的项目，加油

**Comment by cnRicky** [comment]
> https://www.sqlsec.com/2020/02/keledge.html

老哥加油，等着你的自动化脚本

**Comment by sqlsec** [comment]
统一回复一下：2020年2月10日 7.26 可知平台暂时关闭开放阅读了 书籍全部采用试读 =，= 没想到凉的这么快 看来这只东西还是不方便公开

**Comment by cnRicky** [comment]
好的，老哥辛苦了




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "国光"<notifications@github.com&gt;; 
发送时间: 2020年2月10日(星期一) 上午7:29
收件人: "kajweb/wqxuetang_downloader"<wqxuetang_downloader@noreply.github.com&gt;; 
抄送: "Coco"<3191378281@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [kajweb/wqxuetang_downloader] 测试可知平台可以弯道超车下载悦读平台的电子书 有大佬要来完善脚本吗 (#71)




统一回复一下：2020年2月10日 7.26 可知平台暂时关闭开放阅读了 书籍全部采用试读 =，= 没想到凉的这么快 看来这只东西还是不方便公开
