### ISSUE TITLE
下载的图片是缩略图

### ISSUE THREAD

**Issue by kiualen** [kajweb/wqxuetang_downloader#72]
下载的图片是缩略图

**Comment by BillXuce** [comment]
问题已知

**Comment by lovejun277** [comment]
我™心态崩了啊~下了一个下午 结果全是模糊不清的 我还以为我眼花 昨晚看片看多了呢~




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "BillXuce"<notifications@github.com&gt;; 
发送时间: 2020年2月9日(星期天) 晚上7:31
收件人: "kajweb/wqxuetang_downloader"<wqxuetang_downloader@noreply.github.com&gt;; 
抄送: "Subscribed"<subscribed@noreply.github.com&gt;; 
主题: Re: [kajweb/wqxuetang_downloader] 下载的图片是缩略图 (#72)




问题已知

**Comment by xmdt** [comment]
> 问题已知

我刚上文泉学堂的网站上看了下，图片是先出缩略图(10K~12K)，然后出清晰图(100K以上)。以前貌似直接出清晰图~~
看上去可能会出两张图，是不是根据文件大小筛选一下？
ps 可能存在一些占位用的空白页面也被筛去（这些空白或者文字很少的页面本来就比较小）

**Comment by lovejun277** [comment]
求解决~

**Comment by kajweb** [comment]
到[#67 ]统一处理，谢谢。你也可以点击上方的[watch]关注更新，等解决后会第一时间push上来。
