### ISSUE TITLE
合成pdf的时候出BUG了

### ISSUE THREAD

**Issue by litengde** [kajweb/wqxuetang_downloader#9]
好像是PNG转换成JPG造成的

**Comment by kajweb** [comment]
图片貌似一直都是png图片，只是这里命名为jpg了而已。
你那边报什么错？

**Comment by Kuoliang-Chung** [comment]
这个问题应该是和下到了打不开的图片有关，最后合成时都会报错。

**Comment by kajweb** [comment]
删除打不开的图片，然后重新开启任务即可。

新版本已经尽可能减少了无法打开的图片了。
